package io.github.ntufar.kroton.domain

import io.github.ntufar.kroton.model.Equipment
import io.github.ntufar.kroton.model.Equipment.BARBELL
import io.github.ntufar.kroton.model.Equipment.BODYWEIGHT
import io.github.ntufar.kroton.model.Equipment.CABLE
import io.github.ntufar.kroton.model.Equipment.DUMBBELL
import io.github.ntufar.kroton.model.Equipment.EZ_BAR
import io.github.ntufar.kroton.model.Equipment.KETTLEBELL
import io.github.ntufar.kroton.model.Equipment.MACHINE
import io.github.ntufar.kroton.model.Equipment.SMITH
import io.github.ntufar.kroton.model.ExerciseType
import io.github.ntufar.kroton.model.ExerciseType.BODYWEIGHT_REPS
import io.github.ntufar.kroton.model.ExerciseType.WEIGHT_REPS
import io.github.ntufar.kroton.model.Force
import io.github.ntufar.kroton.model.Force.PULL
import io.github.ntufar.kroton.model.Force.PUSH
import io.github.ntufar.kroton.model.Force.STATIC
import io.github.ntufar.kroton.model.Mechanic
import io.github.ntufar.kroton.model.Mechanic.COMPOUND
import io.github.ntufar.kroton.model.Mechanic.ISOLATION
import io.github.ntufar.kroton.model.MuscleGroup
import io.github.ntufar.kroton.model.MuscleGroup.ABS
import io.github.ntufar.kroton.model.MuscleGroup.BICEPS
import io.github.ntufar.kroton.model.MuscleGroup.CALVES
import io.github.ntufar.kroton.model.MuscleGroup.CHEST
import io.github.ntufar.kroton.model.MuscleGroup.FRONT_DELTS
import io.github.ntufar.kroton.model.MuscleGroup.GLUTES
import io.github.ntufar.kroton.model.MuscleGroup.HAMSTRINGS
import io.github.ntufar.kroton.model.MuscleGroup.LATS
import io.github.ntufar.kroton.model.MuscleGroup.LOWER_BACK
import io.github.ntufar.kroton.model.MuscleGroup.OBLIQUES
import io.github.ntufar.kroton.model.MuscleGroup.QUADS
import io.github.ntufar.kroton.model.MuscleGroup.REAR_DELTS
import io.github.ntufar.kroton.model.MuscleGroup.SIDE_DELTS
import io.github.ntufar.kroton.model.MuscleGroup.TRAPS
import io.github.ntufar.kroton.model.MuscleGroup.TRICEPS
import io.github.ntufar.kroton.model.MuscleGroup.UPPER_BACK

/**
 * A minimal hand-curated seed catalogue used until the full free-exercise-db import
 * (spec §7.1, ~250 exercises) lands. Names/categorisation only — no imported description text.
 */
data class SeedExercise(
    val seedUuid: String,
    val name: String,
    val exerciseType: ExerciseType,
    val equipment: Equipment,
    val primaryMuscle: MuscleGroup,
    val secondaryMuscles: List<MuscleGroup> = emptyList(),
    val force: Force?,
    val mechanic: Mechanic?,
    val defaultRestSec: Int? = 90,
)

object SeededExercises {
    val all: List<SeedExercise> =
        listOf(
            SeedExercise(
                "seed-barbell-bench-press",
                "Barbell Bench Press",
                WEIGHT_REPS,
                BARBELL,
                CHEST,
                listOf(TRICEPS, FRONT_DELTS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-incline-barbell-bench-press",
                "Incline Barbell Bench Press",
                WEIGHT_REPS,
                BARBELL,
                CHEST,
                listOf(FRONT_DELTS, TRICEPS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-dumbbell-bench-press",
                "Dumbbell Bench Press",
                WEIGHT_REPS,
                DUMBBELL,
                CHEST,
                listOf(TRICEPS, FRONT_DELTS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-incline-dumbbell-press",
                "Incline Dumbbell Press",
                WEIGHT_REPS,
                DUMBBELL,
                CHEST,
                listOf(FRONT_DELTS, TRICEPS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-dumbbell-fly",
                "Dumbbell Fly",
                WEIGHT_REPS,
                DUMBBELL,
                CHEST,
                emptyList(),
                PUSH,
                ISOLATION,
            ),
            SeedExercise(
                "seed-cable-crossover",
                "Cable Crossover",
                WEIGHT_REPS,
                CABLE,
                CHEST,
                emptyList(),
                PUSH,
                ISOLATION,
            ),
            SeedExercise(
                "seed-push-up",
                "Push-Up",
                BODYWEIGHT_REPS,
                BODYWEIGHT,
                CHEST,
                listOf(TRICEPS, FRONT_DELTS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-dip",
                "Dip",
                BODYWEIGHT_REPS,
                BODYWEIGHT,
                CHEST,
                listOf(TRICEPS, FRONT_DELTS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-barbell-row",
                "Barbell Row",
                WEIGHT_REPS,
                BARBELL,
                UPPER_BACK,
                listOf(LATS, BICEPS),
                PULL,
                COMPOUND,
            ),
            SeedExercise(
                "seed-pendlay-row",
                "Pendlay Row",
                WEIGHT_REPS,
                BARBELL,
                UPPER_BACK,
                listOf(LATS, BICEPS),
                PULL,
                COMPOUND,
            ),
            SeedExercise(
                "seed-dumbbell-row",
                "One-Arm Dumbbell Row",
                WEIGHT_REPS,
                DUMBBELL,
                LATS,
                listOf(UPPER_BACK, BICEPS),
                PULL,
                COMPOUND,
            ),
            SeedExercise(
                "seed-lat-pulldown",
                "Lat Pulldown",
                WEIGHT_REPS,
                CABLE,
                LATS,
                listOf(BICEPS, UPPER_BACK),
                PULL,
                COMPOUND,
            ),
            SeedExercise(
                "seed-seated-cable-row",
                "Seated Cable Row",
                WEIGHT_REPS,
                CABLE,
                UPPER_BACK,
                listOf(LATS, BICEPS),
                PULL,
                COMPOUND,
            ),
            SeedExercise(
                "seed-pull-up",
                "Pull-Up",
                BODYWEIGHT_REPS,
                BODYWEIGHT,
                LATS,
                listOf(BICEPS, UPPER_BACK),
                PULL,
                COMPOUND,
            ),
            SeedExercise(
                "seed-chin-up",
                "Chin-Up",
                BODYWEIGHT_REPS,
                BODYWEIGHT,
                LATS,
                listOf(BICEPS, UPPER_BACK),
                PULL,
                COMPOUND,
            ),
            SeedExercise(
                "seed-deadlift",
                "Deadlift",
                WEIGHT_REPS,
                BARBELL,
                LOWER_BACK,
                listOf(HAMSTRINGS, GLUTES, TRAPS),
                PULL,
                COMPOUND,
            ),
            SeedExercise(
                "seed-romanian-deadlift",
                "Romanian Deadlift",
                WEIGHT_REPS,
                BARBELL,
                HAMSTRINGS,
                listOf(GLUTES, LOWER_BACK),
                PULL,
                COMPOUND,
            ),
            SeedExercise(
                "seed-back-extension",
                "Back Extension",
                BODYWEIGHT_REPS,
                BODYWEIGHT,
                LOWER_BACK,
                listOf(GLUTES, HAMSTRINGS),
                PULL,
                ISOLATION,
            ),
            SeedExercise(
                "seed-overhead-press",
                "Barbell Overhead Press",
                WEIGHT_REPS,
                BARBELL,
                FRONT_DELTS,
                listOf(SIDE_DELTS, TRICEPS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-dumbbell-shoulder-press",
                "Dumbbell Shoulder Press",
                WEIGHT_REPS,
                DUMBBELL,
                FRONT_DELTS,
                listOf(SIDE_DELTS, TRICEPS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-lateral-raise",
                "Dumbbell Lateral Raise",
                WEIGHT_REPS,
                DUMBBELL,
                SIDE_DELTS,
                emptyList(),
                PUSH,
                ISOLATION,
            ),
            SeedExercise(
                "seed-front-raise",
                "Dumbbell Front Raise",
                WEIGHT_REPS,
                DUMBBELL,
                FRONT_DELTS,
                emptyList(),
                PUSH,
                ISOLATION,
            ),
            SeedExercise(
                "seed-rear-delt-fly",
                "Rear Delt Fly",
                WEIGHT_REPS,
                DUMBBELL,
                REAR_DELTS,
                listOf(UPPER_BACK),
                PULL,
                ISOLATION,
            ),
            SeedExercise(
                "seed-face-pull",
                "Cable Face Pull",
                WEIGHT_REPS,
                CABLE,
                REAR_DELTS,
                listOf(UPPER_BACK, TRAPS),
                PULL,
                ISOLATION,
            ),
            SeedExercise(
                "seed-barbell-shrug",
                "Barbell Shrug",
                WEIGHT_REPS,
                BARBELL,
                TRAPS,
                emptyList(),
                PULL,
                ISOLATION,
            ),
            SeedExercise(
                "seed-barbell-curl",
                "Barbell Curl",
                WEIGHT_REPS,
                BARBELL,
                BICEPS,
                emptyList(),
                PULL,
                ISOLATION,
            ),
            SeedExercise("seed-ez-bar-curl", "EZ-Bar Curl", WEIGHT_REPS, EZ_BAR, BICEPS, emptyList(), PULL, ISOLATION),
            SeedExercise(
                "seed-dumbbell-curl",
                "Dumbbell Curl",
                WEIGHT_REPS,
                DUMBBELL,
                BICEPS,
                emptyList(),
                PULL,
                ISOLATION,
            ),
            SeedExercise(
                "seed-hammer-curl",
                "Hammer Curl",
                WEIGHT_REPS,
                DUMBBELL,
                BICEPS,
                listOf(TRICEPS),
                PULL,
                ISOLATION,
            ),
            SeedExercise(
                "seed-triceps-pushdown",
                "Cable Triceps Pushdown",
                WEIGHT_REPS,
                CABLE,
                TRICEPS,
                emptyList(),
                PUSH,
                ISOLATION,
            ),
            SeedExercise(
                "seed-skull-crusher",
                "Skull Crusher",
                WEIGHT_REPS,
                EZ_BAR,
                TRICEPS,
                emptyList(),
                PUSH,
                ISOLATION,
            ),
            SeedExercise(
                "seed-overhead-triceps-extension",
                "Overhead Triceps Extension",
                WEIGHT_REPS,
                DUMBBELL,
                TRICEPS,
                emptyList(),
                PUSH,
                ISOLATION,
            ),
            SeedExercise(
                "seed-close-grip-bench-press",
                "Close-Grip Bench Press",
                WEIGHT_REPS,
                BARBELL,
                TRICEPS,
                listOf(CHEST, FRONT_DELTS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-back-squat",
                "Barbell Back Squat",
                WEIGHT_REPS,
                BARBELL,
                QUADS,
                listOf(GLUTES, HAMSTRINGS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-front-squat",
                "Barbell Front Squat",
                WEIGHT_REPS,
                BARBELL,
                QUADS,
                listOf(GLUTES),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-smith-machine-squat",
                "Smith Machine Squat",
                WEIGHT_REPS,
                SMITH,
                QUADS,
                listOf(GLUTES, HAMSTRINGS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-leg-press",
                "Leg Press",
                WEIGHT_REPS,
                MACHINE,
                QUADS,
                listOf(GLUTES, HAMSTRINGS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-walking-lunge",
                "Walking Lunge",
                WEIGHT_REPS,
                DUMBBELL,
                QUADS,
                listOf(GLUTES, HAMSTRINGS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-bulgarian-split-squat",
                "Bulgarian Split Squat",
                WEIGHT_REPS,
                DUMBBELL,
                QUADS,
                listOf(GLUTES, HAMSTRINGS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-leg-extension",
                "Leg Extension",
                WEIGHT_REPS,
                MACHINE,
                QUADS,
                emptyList(),
                PUSH,
                ISOLATION,
            ),
            SeedExercise(
                "seed-leg-curl",
                "Seated Leg Curl",
                WEIGHT_REPS,
                MACHINE,
                HAMSTRINGS,
                emptyList(),
                PULL,
                ISOLATION,
            ),
            SeedExercise(
                "seed-hip-thrust",
                "Barbell Hip Thrust",
                WEIGHT_REPS,
                BARBELL,
                GLUTES,
                listOf(HAMSTRINGS),
                PUSH,
                COMPOUND,
            ),
            SeedExercise(
                "seed-glute-bridge",
                "Glute Bridge",
                BODYWEIGHT_REPS,
                BODYWEIGHT,
                GLUTES,
                listOf(HAMSTRINGS),
                PUSH,
                ISOLATION,
            ),
            SeedExercise(
                "seed-standing-calf-raise",
                "Standing Calf Raise",
                WEIGHT_REPS,
                MACHINE,
                CALVES,
                emptyList(),
                PUSH,
                ISOLATION,
            ),
            SeedExercise(
                "seed-seated-calf-raise",
                "Seated Calf Raise",
                WEIGHT_REPS,
                MACHINE,
                CALVES,
                emptyList(),
                PUSH,
                ISOLATION,
            ),
            SeedExercise("seed-plank", "Plank", BODYWEIGHT_REPS, BODYWEIGHT, ABS, listOf(OBLIQUES), STATIC, ISOLATION),
            SeedExercise(
                "seed-hanging-leg-raise",
                "Hanging Leg Raise",
                BODYWEIGHT_REPS,
                BODYWEIGHT,
                ABS,
                emptyList(),
                PULL,
                ISOLATION,
            ),
            SeedExercise("seed-cable-crunch", "Cable Crunch", WEIGHT_REPS, CABLE, ABS, emptyList(), PULL, ISOLATION),
            SeedExercise(
                "seed-russian-twist",
                "Russian Twist",
                BODYWEIGHT_REPS,
                BODYWEIGHT,
                OBLIQUES,
                listOf(ABS),
                STATIC,
                ISOLATION,
            ),
            SeedExercise(
                "seed-kettlebell-swing",
                "Kettlebell Swing",
                WEIGHT_REPS,
                KETTLEBELL,
                GLUTES,
                listOf(HAMSTRINGS, LOWER_BACK),
                PULL,
                COMPOUND,
            ),
            SeedExercise(
                "seed-goblet-squat",
                "Goblet Squat",
                WEIGHT_REPS,
                KETTLEBELL,
                QUADS,
                listOf(GLUTES),
                PUSH,
                COMPOUND,
            ),
        )
}
